# GitGuardian configuration file
# Examples: https://github.com/GitGuardian/ggshield/blob/main/.gitguardian.example.yml

secret:
  # Exclude files and paths by globbing
  ignored_paths:
    - README.md
